include:
  - board: nice_nano/nrf52840/zmk
    shield: corne_left_v1_5col
  - board: nice_nano/nrf52840/zmk
    shield: corne_right_v1_5col
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
